/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as NovaComandaRouteImport } from './routes/nova-comanda'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as ImpressorasRouteImport } from './routes/impressoras'
import { Route as GarconsRouteImport } from './routes/garcons'
import { Route as GarcomRouteImport } from './routes/garcom'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComandasRouteImport } from './routes/comandas'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaComandaRoute = NovaComandaRouteImport.update({
  id: '/nova-comanda',
  path: '/nova-comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasRoute = ImpressorasRouteImport.update({
  id: '/impressoras',
  path: '/impressoras',
  getParentRoute: () => rootRouteImport,
} as any)
const GarconsRoute = GarconsRouteImport.update({
  id: '/garcons',
  path: '/garcons',
  getParentRoute: () => rootRouteImport,
} as any)
const GarcomRoute = GarcomRouteImport.update({
  id: '/garcom',
  path: '/garcom',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandasRoute = ComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/categorias': typeof CategoriasRoute
  '/comandas': typeof ComandasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/garcom': typeof GarcomRoute
  '/garcons': typeof GarconsRoute
  '/impressoras': typeof ImpressorasRoute
  '/mesas': typeof MesasRoute
  '/nova-comanda': typeof NovaComandaRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/categorias': typeof CategoriasRoute
  '/comandas': typeof ComandasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/garcom': typeof GarcomRoute
  '/garcons': typeof GarconsRoute
  '/impressoras': typeof ImpressorasRoute
  '/mesas': typeof MesasRoute
  '/nova-comanda': typeof NovaComandaRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/categorias': typeof CategoriasRoute
  '/comandas': typeof ComandasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/garcom': typeof GarcomRoute
  '/garcons': typeof GarconsRoute
  '/impressoras': typeof ImpressorasRoute
  '/mesas': typeof MesasRoute
  '/nova-comanda': typeof NovaComandaRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/caixa'
    | '/cardapio'
    | '/categorias'
    | '/comandas'
    | '/configuracoes'
    | '/dashboard'
    | '/garcom'
    | '/garcons'
    | '/impressoras'
    | '/mesas'
    | '/nova-comanda'
    | '/produtos'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/caixa'
    | '/cardapio'
    | '/categorias'
    | '/comandas'
    | '/configuracoes'
    | '/dashboard'
    | '/garcom'
    | '/garcons'
    | '/impressoras'
    | '/mesas'
    | '/nova-comanda'
    | '/produtos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/caixa'
    | '/cardapio'
    | '/categorias'
    | '/comandas'
    | '/configuracoes'
    | '/dashboard'
    | '/garcom'
    | '/garcons'
    | '/impressoras'
    | '/mesas'
    | '/nova-comanda'
    | '/produtos'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CaixaRoute: typeof CaixaRoute
  CardapioRoute: typeof CardapioRoute
  CategoriasRoute: typeof CategoriasRoute
  ComandasRoute: typeof ComandasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  GarcomRoute: typeof GarcomRoute
  GarconsRoute: typeof GarconsRoute
  ImpressorasRoute: typeof ImpressorasRoute
  MesasRoute: typeof MesasRoute
  NovaComandaRoute: typeof NovaComandaRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-comanda': {
      id: '/nova-comanda'
      path: '/nova-comanda'
      fullPath: '/nova-comanda'
      preLoaderRoute: typeof NovaComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras': {
      id: '/impressoras'
      path: '/impressoras'
      fullPath: '/impressoras'
      preLoaderRoute: typeof ImpressorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garcons': {
      id: '/garcons'
      path: '/garcons'
      fullPath: '/garcons'
      preLoaderRoute: typeof GarconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garcom': {
      id: '/garcom'
      path: '/garcom'
      fullPath: '/garcom'
      preLoaderRoute: typeof GarcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandas': {
      id: '/comandas'
      path: '/comandas'
      fullPath: '/comandas'
      preLoaderRoute: typeof ComandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CaixaRoute: CaixaRoute,
  CardapioRoute: CardapioRoute,
  CategoriasRoute: CategoriasRoute,
  ComandasRoute: ComandasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  GarcomRoute: GarcomRoute,
  GarconsRoute: GarconsRoute,
  ImpressorasRoute: ImpressorasRoute,
  MesasRoute: MesasRoute,
  NovaComandaRoute: NovaComandaRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
